version: '3.8'

services:
  postgres-chat:
    image: postgres:latest
    container_name: chatdatabase
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: chatdatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-chat-data:/var/lib/postgresql/data


  postgres-users:
    image: postgres:latest
    container_name: userdatabase
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: userdatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-user-data:/var/lib/postgresql/data


  postgres-auth:
    image: postgres:latest
    container_name: authdatabase
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: authdatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U analytics_user -d analyticsdb"]
#      interval: 5s
#      timeout: 5s
#      retries: 5

  cassandra-messages:
    image: bitnami/cassandra:latest
    container_name: cassandra_db
    ports:
      - "9042:9042"
    volumes:
      - cassandra-messages-data:/var/lib/cassandra
      - ./message-storage-service/cassandra-init-scripts:/docker-entrypoint-initdb.d:Z
    environment:
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DATACENTER=datacenter1
      - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
      - CASSANDRA_AUTHORIZER=CassandraAuthorizer
#      - CASSANDRA_AUTHENTICATOR=AllowAllAuthenticator
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -u cassandra -p cassandra -e 'DESCRIBE KEYSPACES'" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - cassandra_network

volumes:
  postgres-chat-data:
  postgres-user-data:
  postgres-auth-data:
  cassandra-messages-data:

networks:
  cassandra_network:
    driver: bridge

