version: '3.8'

services:
  postgres-chat:
    image: postgres:latest
    container_name: chatdatabase
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: chatdatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-chat-data:/var/lib/postgresql/data


  postgres-users:
    image: postgres:latest
    container_name: userdatabase
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: userdatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-user-data:/var/lib/postgresql/data


  postgres-auth:
    image: postgres:latest
    container_name: authdatabase
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: authdatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres-auth-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics_user -d analyticsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    container_name: redis_messaging_service
    ports:
      - "6379:6379"
    volumes:
      - redis-websocket-tokens:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  postgres-chat-data:
  postgres-user-data:
  postgres-auth-data:
  redis-websocket-tokens:

