# Headless Service — обязателен для StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: cassandra-messages
  namespace: messenger
spec:
  clusterIP: None
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    app: cassandra-messages
---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra-messages
  namespace: messenger
spec:
  serviceName: cassandra-messages
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-messages
  template:
    metadata:
      labels:
        app: cassandra-messages
    spec:
      imagePullSecrets:
        - name: gitlab-regcred
      terminationGracePeriodSeconds: 60
      containers:
        - name: cassandra-messages
          image: registry.gitlab.com/liza.antipa/yazikochesalna/cassandra:main
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "nodetool drain && nodetool stopdaemon"]
          ports:
            - containerPort: 9042
          envFrom:
            - configMapRef:
                name: cassandra-messages-config
            - secretRef:
                name: cassandra-messages-secrets
          env:
            - name: MAX_HEAP_SIZE
              value: "4G"
            - name: HEAP_NEWSIZE
              value: "1G"
          volumeMounts:
            - name: cassandra-messages-data
              mountPath: /var/lib/cassandra
            - name: cassandra-init-flag
              mountPath: /bitnami/cassandra/initialized
          livenessProbe:
            exec:
              command: ["sh", "-c", "cqlsh -u \"$CASSANDRA_USER\" -p \"$CASSANDRA_PASSWORD\" localhost 9042 -e \"DESCRIBE KEYSPACES\""]
            initialDelaySeconds: 320
            periodSeconds: 20
            failureThreshold: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "-c", "cqlsh -u \"$CASSANDRA_USER\" -p \"$CASSANDRA_PASSWORD\" localhost 9042 -e \"SELECT keyspace_name FROM system_schema.keyspaces WHERE keyspace_name = 'storage_service_keyspace'\""]
            initialDelaySeconds: 310
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: "1000m"
              memory: "7Gi"
  volumeClaimTemplates:
    - metadata:
        name: cassandra-messages-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: cassandra-init-flag
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
---
# Обычный Service для внешнего доступа
apiVersion: v1
kind: Service
metadata:
  name: cassandra-messages-lb
  namespace: messenger
spec:
  ports:
    - port: 9042
      targetPort: 9042
  selector:
    app: cassandra-messages