apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-file-storage
  labels:
    app: minio-file-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-file-storage
  template:
    metadata:
      labels:
        app: minio-file-storage
    spec:
      containers:
        - name: minio-file-storage
          image: minio/minio:latest
          command: ["server", "--console-address", ":9001", "/data/"]
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          envFrom:
            - secretRef:
                name: minio-file-storage-secrets
          volumeMounts:
            - name: storage
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: minio-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: minio-file-storage
spec:
  selector:
    app: minio-file-storage
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP
