apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-file-storage
spec:
  serviceName: minio-file-storage-headless
  replicas: 1
  selector:
    matchLabels:
      app: minio-file-storage
  template:
    metadata:
      labels:
        app: minio-file-storage
    spec:
      containers:
        - name: minio-file-storage
          image: minio/minio:latest
#          command: ["/bin/sh", "-c"]
#          args:
#            - "minio server --console-address :9001 /data"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          envFrom:
            - secretRef:
                name: minio-file-storage-secrets
          volumeMounts:
            - name: storage
              mountPath: /data
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
---
# ClusterIP Service — для внешнего доступа
apiVersion: v1
kind: Service
metadata:
  name: minio-file-storage
spec:
  ports:
    - name: api
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: minio-file-storage
  type: ClusterIP

---
# Headless Service — обязателен для StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: minio-file-storage-headless
spec:
  clusterIP: None
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  selector:
    app: minio-file-storage