apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-chat
  labels:
    app: postgres-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-chat
  template:
    metadata:
      labels:
        app: postgres-chat
    spec:
      containers:
        - name: postgres-chat
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-chat-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-chat-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-chat-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-chat-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-chat-data
          persistentVolumeClaim:
            claimName: postgres-chat-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-chat
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-chat
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-chat-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
