apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-users
  labels:
    app: postgres-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-users
  template:
    metadata:
      labels:
        app: postgres-users
    spec:
      containers:
        - name: postgres-users
          image: postgres:latest
          lifecycle:
            preStop:
              exec:
                # Остановка PostgreSQL перед завершением контейнера
                command: [ "sh", "-c", "pg_ctl stop -D /var/lib/postgresql/data -w -t 60 -m fast" ]
          terminationGracePeriodSeconds: 70
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-users-config
            - secretRef:
                name: postgres-users-secrets
          volumeMounts:
            - name: postgres-user-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: [ "sh", "-c", 'pg_isready -U "$POSTGRES_USER" -d postgres ' ]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command: [ "sh", "-c", 'pg_isready -U "$POSTGRES_USER" -d postgres' ]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
      volumes:
        - name: postgres-user-data
          persistentVolumeClaim:
            claimName: postgres-user-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-users
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-users
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
