# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-auth
spec:
  serviceName: postgres-auth
  replicas: 1
  selector:
    matchLabels:
      app: postgres-auth
  template:
    metadata:
      labels:
        app: postgres-auth
    spec:
      imagePullSecrets:
        - name: dockerhub-regcred-secret
      terminationGracePeriodSeconds: 70
      containers:
        - name: postgres-auth
          image: postgres:latest
          lifecycle:
            preStop:
              exec:
                # Корректное завершение Postgres
                command: ["sh", "-c", "pg_ctl stop -D /var/lib/postgresql/data -w -t 60 -m fast"]
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-auth-config
            - secretRef:
                name: postgres-auth-secrets
          volumeMounts:
            - name: postgres-auth-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d postgres"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d postgres"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
  volumeClaimTemplates:
    - metadata:
        name: postgres-auth-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---

# Headless Service (обязательно для StatefulSet)
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-auth

---

# Обычный Service для внешнего доступа
apiVersion: v1
kind: Service
metadata:
  name: postgres-auth-lb
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-auth