# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-users
spec:
  serviceName: postgres-users
  replicas: 1
  selector:
    matchLabels:
      app: postgres-users
  template:
    metadata:
      labels:
        app: postgres-users
    spec:
      terminationGracePeriodSeconds: 70
      containers:
        - name: postgres-users
          image: postgres:latest
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "pg_ctl stop -D /var/lib/postgresql/data -w -t 60 -m fast"]
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-users-config
            - secretRef:
                name: postgres-users-secrets
          volumeMounts:
            - name: postgres-user-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d postgres"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d postgres"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
  volumeClaimTemplates:
    - metadata:
        name: postgres-user-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
# Headless Service — обязателен для StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: postgres-users
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-users

---
# Обычный Service для внешнего доступа
apiVersion: v1
kind: Service
metadata:
  name: postgres-users-lb
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-users