# Headless Service — обязателен для StatefulSet
apiVersion: v1
kind: Service
meta
  name: postgres-chat
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-chat
---
# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
meta
  name: postgres-chat
spec:
  serviceName: postgres-chat
  replicas: 1
  selector:
    matchLabels:
      app: postgres-chat
  template:
    metadata:
      labels:
        app: postgres-chat
    spec:
      terminationGracePeriodSeconds: 70
      containers:
        - name: postgres-chat
          image: postgres:latest
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "pg_ctl stop -D /var/lib/postgresql/data -w -t 60 -m fast"]
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-chat-config
            - secretRef:
                name: postgres-chat-secrets
          volumeMounts:
            - name: postgres-chat-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d postgres"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d postgres"]
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
  volumeClaimTemplates:
    - meta
        name: postgres-chat-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
# LoadBalancer/ClusterIP Service — для внешнего доступа
apiVersion: v1
kind: Service
meta
  name: postgres-chat-lb
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-chat