apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-websocket-tokens
  labels:
    app: redis-websocket-tokens
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-websocket-tokens
  template:
    metadata:
      labels:
        app: redis-websocket-tokens
    spec:
      containers:
        - name: redis-websocket-tokens
          image: redis:7.0-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-websocket-tokens
              mountPath: /data
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 5
      volumes:
        - name: redis-websocket-tokens
          persistentVolumeClaim:
            claimName: redis-websocket-tokens-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-websocket-tokens
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis-websocket-tokens
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-websocket-tokens-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
