apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-service-config
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-chat.messenger.svc.cluster.local:5432/chatdatabase"
  SPRING_DATASOURCE_HOST: "postgres-chats.messenger.svc.cluster.local"
  SPRING_DATASOURCE_PORT: "5432"
  SPRING_DATASOURCE_DATABASE: "chatdatabase"