apiVersion: v1
kind: ConfigMap
metadata:
  name: messaging-service-config
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-message-storage.messenger.svc.cluster.local:9092"
  REDIS_HOST: "redis-websocket-tokens.messenger.svc.cluster.local"
  REDIS_PORT: "6379"
