apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  SERVER_PORT: "8083"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-users-lb.messenger.svc.cluster.local:5432/userdatabase"
  SPRING_DATASOURCE_HOST: "postgres-users-lb.messenger.svc.cluster.local"
  SPRING_DATASOURCE_PORT: "5432"
  SPRING_DATASOURCE_DATABASE: "userdatabase"
  SPRING_ELASTICSEARCH_URIS: "http://elasticsearch-users-search.messenger.svc.cluster.local:9200"
