apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      imagePullSecrets:
        - name: gitlab-regcred
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ "/bin/sh", "-c", "until nc -z postgres-chat.messenger.svc.cluster.local 5432; do echo waiting for postgres-auth; sleep 5; done; echo postgres-auth is up;" ]
      containers:
        - name: chat-service
          image: registry.gitlab.com/liza.antipa/yazikochesalna/chat-service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: chat-service-config
            - secretRef:
                name: chat-service-secrets
            - configMapRef:
                name: general-service-config
            - secretRef:
                name: general-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: chat-service
