apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-storage-service
  template:
    metadata:
      labels:
        app: message-storage-service
    spec:
      imagePullSecrets:
        - name: gitlab-regcred
      initContainers:
        - name: wait-for-kafka
          image: busybox
          command: [ 'sh', '-c', 'until nc -z kafka-message-storage.messenger.svc.cluster.local 9092; do echo waiting for Kafka; sleep 5; done;' ]
        - name: wait-for-cassandra
          image: bitnami/cassandra:latest
          command: ['sh', '-c', 'until cqlsh -u db_admin -p 1234 cassandra-messages.messenger.svc.cluster.local 9042 -e "SELECT keyspace_name FROM system_schema.keyspaces WHERE keyspace_name = ''storage_service_keyspace''" | grep storage_service_keyspace; do echo "waiting for Cassandra keyspace storage_service_keyspace"; sleep 5; done;']
      containers:
        - name: message-storage-service
          image: registry.gitlab.com/liza.antipa/yazikochesalna/message-storage-service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-message-storage.messenger.svc.cluster.local:9092"
            - name: SPRING_CASSANDRA_CONTACT_POINTS
              value: "cassandra-messages.messenger.svc.cluster.local"
            - name: SPRING_CASSANDRA_PORT
              value: "9042"
            - name: SPRING_CASSANDRA_USERNAME
              value: "db_admin"
            - name: SPRING_CASSANDRA_PASSWORD
              value: "1234"
            - name: JWT_SECRET_KEY
              value: "5d1a51090ece358e6afa19650833608a44732a9a6251cbd4c6e1cb0ca2eb6735d439efc354d1fccd73f461124023f4cea4020de8efaf57843e4c63d8296bc7f9"
            - name: JWT_ACCESS_TOKEN_EXPIRATION
              value: "36000000"
            - name: JWT_REFRESH_TOKEN_EXPIRATION
              value: "252000000"
            - name: WEBCLIENT_TIMEOUT
              value: "50000"
            - name: CHAT_SERVICE_URL
              value: "http://chat-service.messenger.svc.cluster.local:8080"
            - name: MESSAGE_STORAGE_SERVICE_URL
              value: "http://message-storage-service.messenger.svc.cluster.local:8081"
            - name: MESSAGING_SERVICE_URL
              value: "http://messaging-service.messenger.svc.cluster.local:8082"
            - name: USER_SERVICE_URL
              value: "http://user-service.messenger.svc.cluster.local:8083"
            - name: AUTHORIZATION_SERVICE_URL
              value: "http://authorization-service.messenger.svc.cluster.local:8085"
            - name: FRONT_SERVER_URL
              value: "http://front-server.messenger.svc.cluster.local:5173"
---
apiVersion: v1
kind: Service
metadata:
  name: message-storage-service
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: message-storage-service
