apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: gitlab-regcred
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: [ "/bin/sh", "-c", "until nc -z postgres-users.messenger.svc.cluster.local 5432; do echo waiting for postgres-users; sleep 5; done; echo postgres-user is up;" ]
      containers:
        - name: user-service
          image: registry.gitlab.com/liza.antipa/yazikochesalna/user-service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secrets
            - configMapRef:
                name: general-service-config
            - secretRef:
                name: general-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: user-service
