apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      imagePullSecrets:
        - name: gitlab-regcred
      initContainers:
        - name: wait-for-postgres
          image: postgres:latest
          env:
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: SPRING_DATASOURCE_HOST
            - name: PG_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: SPRING_DATASOURCE_PORT
            - name: PG_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: user-service-config
                  key: SPRING_DATASOURCE_DATABASE
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: SPRING_DATASOURCE_USERNAME
          command: ["sh", "-c", "until pg_isready -h $PG_HOST -p $PG_PORT -U $PG_USERNAME -d postgres; do echo 'waiting for postgres-chat'; sleep 5; done; echo 'postgres-chat is up';"]
      containers:
        - name: user-service
          image: registry.gitlab.com/liza.antipa/yazikochesalna/user-service:main
          imagePullPolicy: Always
#          resources:
#            limits:
#              cpu: "10m"
#              memory: "256Mi"
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: user-service-config
            - secretRef:
                name: user-service-secrets
            - configMapRef:
                name: general-service-config
            - secretRef:
                name: general-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: user-service
