apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: messenger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: JWT_SECRET_KEY
              value: "5d1a51090ece358e6afa19650833608a44732a9a6251cbd4c6e1cb0ca2eb6735d439efc354d1fccd73f461124023f4cea4020de8efaf57843e4c63d8296bc7f9"
            - name: JWT_ACCESS_TOKEN_EXPIRATION
              value: "36000000"
            - name: JWT_REFRESH_TOKEN_EXPIRATION
              value: "252000000"
            - name: WEBCLIENT_TIMEOUT
              value: "50000"
            - name: CHAT_SERVICE_URL
              value: "http://chat-service.messenger.svc.cluster.local:8080"
            - name: MESSAGE_STORAGE_SERVICE_URL
              value: "http://message-storage-service.messenger.svc.cluster.local:8081"
            - name: MESSAGING_SERVICE_URL
              value: "http://messaging-service.messenger.svc.cluster.local:8082"
            - name: USER_SERVICE_URL
              value: "http://user-service.messenger.svc.cluster.local:8083"
            - name: AUTHORIZATION_SERVICE_URL
              value: "http://authorization-service.messenger.svc.cluster.local:8085"
            - name: FRONT_SERVER_URL
              value: "http://front-server.messenger.svc.cluster.local:5173"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: messenger
spec:
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: user-service
