apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-message-storage-config
data:
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_NODE_ID: "1"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-message-storage.messenger.svc.cluster.local:9093"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_LOCAL://localhost:9094,CONTROLLER://0.0.0.0:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-message-storage.messenger.svc.cluster.local:9092,PLAINTEXT_LOCAL://localhost:9094"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  CLUSTER_ID: "kafka-message-storage-cluster-1"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_LOCAL:PLAINTEXT,CONTROLLER:PLAINTEXT"