apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: messenger
resources:
  - ../../base

  - secrets/gitlab-regcred-secret.yaml
  - secrets/microservices/auth-service-secrets.yaml
  - secrets/microservices/general-service-secrets.yaml
  - secrets/microservices/chat-service-secrets.yaml
  - secrets/microservices/message-storage-service-secrets.yaml
  - secrets/microservices/user-service-secrets.yaml
  - secrets/microservices/file-service-secrets.yaml
  - secrets/dependencies/cassandra-messages-secrets.yaml
  - secrets/dependencies/postgres-auth-secrets.yaml
  - secrets/dependencies/postgres-chat-secrets.yaml
  - secrets/dependencies/postgres-users-secrets.yaml
  - secrets/dependencies/minio-file-storage-secrets.yaml
  - secrets/tls/tls-secret-generator.yaml

  - configmaps/microservices/general-service-config.yaml
  - configmaps/microservices/auth-service-config.yaml
  - configmaps/microservices/chat-service-config.yaml
  - configmaps/microservices/message-storage-service-config.yaml
  - configmaps/microservices/messaging-service-config.yaml
  - configmaps/microservices/user-service-config.yaml
  - configmaps/microservices/file-service-config.yaml
  - configmaps/dependencies/cassandra-messages-config.yaml
  - configmaps/dependencies/kafka-message-storage-config.yaml
  - configmaps/dependencies/postgres-auth-config.yaml
  - configmaps/dependencies/postgres-chat-config.yaml
  - configmaps/dependencies/postgres-users-config.yaml
